In [39]:
import pandas as pd
import random
import numpy as np

user_log = pd.read_csv('./cf_model.csv')

In [49]:
user_log

        user_idx     id
0              0  11602
1              0   6080
2              0   2385
3              0   6076
4              0   6077
...          ...    ...
241739     45586   4773
241740     45587   6600
241741     45587   5061
241742     45587  11955
241743     45587   5706

[241744 rows x 2 columns]

In [41]:
grouped = user_log.groupby('user_idx').count()
grouped = grouped[~grouped['id'].isin([1, 2])].reset_index() # 게임기록이 1,2개뿐인 유저는 학습에 사용 불가 따라서 제거

In [42]:
grouped

       user_idx  id
0             0   5
1             2   9
2             3   7
3             4  10
4             5   9
...         ...  ..
39361     45582   6
39362     45584   5
39363     45585   4
39364     45586   4
39365     45587   4

[39366 rows x 2 columns]

In [43]:
# 딕셔너리 생성
user_dict = dict(zip(grouped['user_idx'], grouped['id']//3))

In [44]:
train_set = pd.DataFrame(columns=['user_idx', 'id'])
test_set = pd.DataFrame(columns=['user_idx', 'id'])

In [46]:
random.seed(42) # 시드 고정

for k, v in user_dict.items():
    tmp_df = user_log[user_log['user_idx'] == k]
    
    # 데이터프레임에서 user_idx 열을 리스트로 변환
    user_idx_list = tmp_df['id'].unique().tolist()

    # 랜덤으로 2개의 user_idx 선택
    random_user_idx = random.sample(user_idx_list, k=v)

    # 선택되지 않은 user_idx 추출
    left_user_idx = [user_idx for user_idx in user_idx_list if user_idx not in random_user_idx]

    # 해당 user_idx를 가지고 train-test set을 만들기
    tmp_train_df = tmp_df[tmp_df['id'].isin(left_user_idx)]
    tmp_test_df = tmp_df[tmp_df['id'].isin(random_user_idx)]
    
    train_set = pd.concat([train_set,tmp_train_df])
    test_set = pd.concat([test_set,tmp_test_df])

In [47]:
train_set

       user_idx     id
1             0   6080
2             0   2385
3             0   6076
4             0   6077
8             2  11935
...         ...    ...
241737    45586    511
241739    45586   4773
241740    45587   6600
241741    45587   5061
241742    45587  11955

[166312 rows x 2 columns]

In [48]:
test_set

       user_idx     id
0             0  11602
6             2   4917
7             2   9200
10            2   9596
16            3   7300
...         ...    ...
241724    45582   9663
241727    45584  11100
241735    45585  11100
241738    45586   7667
241743    45587   5706

[68117 rows x 2 columns]

In [50]:
train_set.to_csv('./train_set.csv', index=False)
test_set.to_csv('./test_set.csv', index=False)

In [ ]:
dfdfdf여기까지ㅇㄹㅇㄹㅇㄹ

In [ ]:
total_user_idx = user_log['user_idx'].unique()

In [ ]:
user_log['id'].value_counts()

id
10986    3454
2203     2146
3331     1427
10820    1323
8508     1264
         ...
9829        1
6393        1
63          1
1236        1
12490       1
Name: count, Length: 9644, dtype: int64

In [ ]:
grouped = user_log.groupby('user_idx').count()

In [ ]:
grouped = grouped.sort_values(by='id', ascending=False)
grouped = grouped[~grouped['id'].isin([1, 2])].reset_index() # 게임기록이 1,2개뿐인 유저는 학습에 사용 불가 따라서 제거

In [ ]:
grouped

       user_idx  id
0           788  19
1          2729  19
2          5269  16
3           429  14
4         12894  14
...         ...  ..
39361     35187   3
39362     33664   3
39363     16815   3
39364     16850   3
39365     33658   3

[39366 rows x 2 columns]

In [ ]:
total_user_idx = grouped['user_idx'].unique()

In [ ]:
grouped['id'].value_counts()

id
3     9517
4     6213
10    5716
5     4511
9     3867
6     3492
8     3056
7     2964
11      22
12       3
19       2
14       2
16       1
Name: count, dtype: int64

전체 유저 39366명 / 이중 20%는 약 7873명

1. 상위 20%로 만들기

In [ ]:
sorted_grouped = grouped.sort_values(by='id', ascending=False)

In [ ]:
tmp = sorted_grouped.head(8800)

In [ ]:
tmp.head(10)

          id
user_idx
788       19
2729      19
5269      16
429       14
12894     14
43258     12
14655     12
28889     12
490       11
12672     11

In [ ]:
tmp.tail()

          id
user_idx
7055       9
530        9
18162      9
27452      9
25735      9

In [ ]:
test_set_idx = tmp.index.get_level_values('user_idx').unique()

In [ ]:
test_set_idx

Index([  788,  2729,  5269,   429, 12894, 43258, 14655, 28889,   490, 12672,
       ...
       32004,   550,   553,   554,  7036,  7055,   530, 18162, 27452, 25735],
      dtype='int64', name='user_idx', length=8800)

2. 비율이 많이 분포하는 지점에서 20% 랜덤 샘플링

In [ ]:
tmp2 = user_log[user_log['id'] == '8']

In [ ]:
tmp2 = grouped[grouped['id'].isin([8, 9, 10])]

In [ ]:
tmp2

          id
user_idx
16637     10
4888      10
4897      10
22807     10
26307     10
...       ..
10143      8
42983      8
21892      8
35454      8
4798       8

[12639 rows x 1 columns]

In [ ]:
user_log[user_log['user_idx'] == 16637]

       user_idx     id
96597     16637  10820
96598     16637  10810
96599     16637   3855
96600     16637   3146
96601     16637  10016
96602     16637  10996
96603     16637   2841
96604     16637   4004
96605     16637   5631
96606     16637  11237

In [ ]:
tmp2

Empty DataFrame
Columns: [user_idx, id]
Index: []

In [ ]:
tmp2 = tmp2.reset_index()
tmp2

       user_idx  id
0             2   9
1             4  10
2             5   9
3             6  10
4             8  10
...         ...  ..
12634     45559  10
12635     45562  10
12636     45564  10
12637     45568   8
12638     45569  10

[12639 rows x 2 columns]

In [ ]:
tmp2['id'].unique()

In [ ]:
tmp2['id'].unique()

array([ 9, 10,  8])

In [ ]:
# 랜덤 시드 고정
np.random.seed(42)

test_set_idx_2 = np.random.choice(tmp2['user_idx'].unique(), size=8800, replace=False)

In [ ]:
test_set_idx_2

array([39080,  2814, 28825, ...,   331,  4107, 27767])

In [ ]:
len(test_set_idx_2)

8800

3. 각 집단별로 20%씩 뽑기

In [ ]:
# 랜덤 시드 고정
np.random.seed(42)
test_set_idx_3 = []

for i in range(1,20):
    tmp3 = grouped[grouped['id'].isin([i])]
    tmp3 = tmp3.reset_index()
    #print(tmp3)
    sampled_df = tmp3.sample(frac=0.2, random_state=42)
    user_idx_list = sampled_df['user_idx'].tolist()
    if user_idx_list :
        test_set_idx_3.append(user_idx_list)
    #print(user_idx_list)
    #print(len(user_idx_list))
    #print('*************************')
    #for j in np.random.choice(tmp3['user_idx'].unique(), size=int(len(tmp3)*0.2), replace=False):
    #    test_set_idx_3.append(j)

In [ ]:
test_set_idx_3

[[21778,
  44839,
  25999,
  17974,
  4578,
  35836,
  28812,
  12637,
  7648,
  14149,
  38997,
  22341,
  16126,
  45122,
  30318,
  17254,
  36753,
  36922,
  33492,
  36236,
  31478,
  44042,
  29260,
  21040,
  33985,
  24465,
  37244,
  13744,
  34209,
  35371,
  43494,
  9655,
  33180,
  4173,
  2573,
  39506,
  18137,
  16518,
  37046,
  45067,
  22674,
  23808,
  19090,
  26604,
  45536,
  19290,
  3763,
  36730,
  13663,
  44350,
  45341,
  23496,
  16914,
  11687,
  23726,
  21506,
  8959,
  12222,
  32537,
  15135,
  15259,
  41700,
  8421,
  5580,
  35427,
  25480,
  3667,
  44906,
  17816,
  44859,
  38735,
  40428,
  38919,
  4518,
  42607,
  38262,
  28017,
  25227,
  11405,
  39563,
  1634,
  42112,
  20887,
  11026,
  21799,
  25509,
  7530,
  45506,
  4161,
  17619,
  19787,
  31189,
  9642,
  45262,
  22650,
  31012,
  40035,
  44892,
  39407,
  21483,
  17105,
  32338,
  20377,
  40836,
  8377,
  16486,
  39083,
  40964,
  25656,
  30869,
  21306,
  20851,
  27235,
  11975,
  17193,
  7105,
  34505,
  21150,
  34208,
  42184,
  38421,
  29656,
  12904,
  19267,
  21722,
  4182,
  44308,
  25902,
  23394,
  24418,
  21273,
  20287,
  45301,
  43235,
  42644,
  45021,
  35043,
  23079,
  35998,
  16337,
  36963,
  41979,
  7970,
  32913,
  28925,
  31793,
  29916,
  39554,
  28292,
  44678,
  13309,
  34170,
  42477,
  43570,
  34580,
  20974,
  34389,
  25957,
  28245,
  19694,
  44788,
  24397,
  4350,
  11507,
  3652,
  10402,
  31165,
  10112,
  11090,
  45078,
  27750,
  1443,
  44146,
  12368,
  40882,
  28315,
  25183,
  45244,
  25376,
  26787,
  43279,
  5655,
  40733,
  36147,
  34394,
  11586,
  30091,
  7450,
  30513,
  18507,
  9505,
  41295,
  21571,
  13392,
  26982,
  17235,
  12330,
  18082,
  21843,
  35297,
  33964,
  6941,
  36347,
  33883,
  42787,
  16694,
  6213,
  16564,
  20239,
  10959,
  19666,
  27857,
  17269,
  41044,
  43802,
  26205,
  27023,
  26752,
  16304,
  39126,
  6688,
  28519,
  21249,
  11110,
  41536,
  22721,
  28157,
  44569,
  14136,
  36855,
  25233,
  3214,
  42808,
  14308,
  30401,
  21645,
  33186,
  7646,
  14739,
  2841,
  29336,
  33606,
  17668,
  37606,
  29136,
  12565,
  31855,
  43178,
  38090,
  37408,
  3125,
  12324,
  38878,
  15563,
  17332,
  13703,
  5116,
  39908,
  35256,
  40823,
  24558,
  12318,
  37845,
  41712,
  34510,
  8908,
  34449,
  26058,
  42567,
  27744,
  9027,
  33253,
  3549,
  15502,
  33867,
  42325,
  33092,
  36613,
  17747,
  21492,
  27726,
  37693,
  16530,
  6175,
  34763,
  16553,
  24289,
  1848,
  20121,
  18638,
  16855,
  11327,
  17815,
  22076,
  1405,
  9634,
  19402,
  18181,
  28165,
  33808,
  24245,
  17929,
  37984,
  38218,
  42333,
  10026,
  17675,
  25542,
  7554,
  14107,
  517,
  44663,
  31844,
  42382,
  28055,
  37892,
  13824,
  24676,
  4396,
  5449,
  30347,
  43874,
  9165,
  27342,
  17922,
  11230,
  25395,
  34890,
  40005,
  22194,
  34766,
  27165,
  38841,
  24393,
  45510,
  2619,
  5265,
  44048,
  15552,
  30302,
  297,
  31915,
  43433,
  13571,
  13129,
  17239,
  38875,
  42894,
  44955,
  5829,
  12288,
  29139,
  4839,
  14500,
  22354,
  14678,
  40838,
  19524,
  18230,
  25693,
  30652,
  4091,
  41558,
  45192,
  9821,
  8061,
  29663,
  17293,
  44857,
  17027,
  29718,
  38170,
  34819,
  43380,
  4051,
  17000,
  26915,
  21148,
  29706,
  27149,
  31052,
  45311,
  8008,
  20587,
  38034,
  9091,
  45019,
  36793,
  18535,
  23677,
  13325,
  33280,
  27622,
  8019,
  38837,
  32855,
  21836,
  749,
  20803,
  30031,
  38306,
  26090,
  24893,
  32159,
  42368,
  12549,
  36082,
  29021,
  21885,
  35061,
  40395,
  39026,
  41488,
  22274,
  32062,
  27167,
  34283,
  34804,
  33751,
  3147,
  42667,
  24254,
  27705,
  45360,
  937,
  41772,
  13048,
  37008,
  4581,
  42326,
  4250,
  37741,
  40195,
  40826,
  20215,
  18087,
  8226,
  18937,
  29372,
  15592,
  8911,
  18886,
  43363,
  20399,
  20709,
  13795,
  33177,
  44709,
  22032,
  12775,
  18620,
  14509,
  18476,
  16956,
  43128,
  19920,
  26673,
  23029,
  42574,
  18450,
  18239,
  20923,
  15030,
  7070,
  22810,
  14766,
  22039,
  13758,
  4209,
  13354,
  35773,
  15219,
  29815,
  12694,
  9897,
  27708,
  45330,
  17207,
  30312,
  25445,
  15091,
  33037,
  16939,
  30669,
  37715,
  6990,
  10256,
  10310,
  10102,
  33478,
  7460,
  22523,
  19303,
  45395,
  38278,
  19371,
  35548,
  32942,
  43964,
  42603,
  17487,
  12299,
  9247,
  39066,
  16847,
  26228,
  20443,
  41768,
  15326,
  8846,
  23265,
  4111,
  18706,
  17885,
  20087,
  28993,
  38485,
  24146,
  42306,
  25452,
  40825,
  5067,
  29169,
  12286,
  28904,
  11434,
  28952,
  26665,
  41483,
  19824,
  21430,
  28770,
  39873,
  13433,
  13719,
  8375,
  8424,
  38074,
  44983,
  42450,
  17608,
  15411,
  4363,
  21814,
  40274,
  33195,
  37478,
  37333,
  22530,
  35606,
  43163,
  7430,
  1946,
  35955,
  8933,
  11095,
  44379,
  6660,
  43132,
  45141,
  2404,
  34637,
  18760,
  31386,
  37637,
  37775,
  12208,
  33989,
  18603,
  39146,
  44962,
  36736,
  24112,
  38070,
  34910,
  39516,
  37454,
  12895,
  41696,
  20482,
  35993,
  33412,
  19473,
  40629,
  44197,
  26369,
  17301,
  23603,
  36108,
  22324,
  8792,
  36853,
  7477,
  43676,
  15620,
  26549,
  32641,
  14855,
  36257,
  20876,
  42194,
  17732,
  44762,
  21429,
  1635,
  15014,
  5509,
  28207,
  32552,
  34826,
  15260,
  19644,
  19560,
  43559,
  24490,
  7829,
  1301,
  17386,
  6591,
  37559,
  35683,
  26884,
  38759,
  25584,
  26001,
  20365,
  38091,
  14145,
  27635,
  33670,
  19908,
  220,
  7783,
  14575,
  24971,
  38708,
  6203,
  2004,
  29619,
  12590,
  45108,
  21406,
  24346,
  27500,
  31747,
  25701,
  19475,
  23658,
  41347,
  13076,
  45195,
  43775,
  15005,
  28658,
  36689,
  36434,
  37279,
  7547,
  5587,
  25742,
  20058,
  13330,
  16760,
  7790,
  19028,
  44040,
  36969,
  43933,
  43755,
  1233,
  42387,
  3949,
  29596,
  33704,
  40820,
  25974,
  42647,
  12771,
  17032,
  11276,
  32115,
  14450,
  19352,
  40544,
  16073,
  44147,
  37050,
  35052,
  35024,
  8189,
  16018,
  15725,
  10793,
  15953,
  42219,
  23215,
  29572,
  8374,
  44726,
  42669,
  16958,
  29979,
  9530,
  29314,
  41820,
  23842,
  39294,
  22230,
  9763,
  34096,
  13742,
  41197,
  40175,
  8661,
  45145,
  23037,
  28842,
  43671,
  22078,
  32607,
  41418,
  15274,
  40932,
  40766,
  13942,
  6924,
  35794,
  10110,
  19643,
  39763,
  27020,
  18682,
  13031,
  9421,
  7943,
  5604,
  23853,
  44490,
  27971,
  14155,
  17196,
  13339,
  18556,
  34968,
  24605,
  16736,
  6648,
  25495,
  31878,
  14522,
  24711,
  9498,
  24064,
  10057,
  42406,
  26183,
  3115,
  33658,
  44232,
  38386,
  13670,
  11559,
  26540,
  24016,
  33722,
  10633,
  40789,
  15790,
  40305,
  38273,
  41519,
  22871,
  30100,
  5154,
  19620,
  24777,
  12620,
  19305,
  44026,
  23156,
  39577,
  25073,
  33353,
  12196,
  3093,
  12617,
  9034,
  25337,
  19263,
  4229,
  28099,
  39572,
  30109,
  26221,
  36854,
  13778,
  15714,
  24879,
  37639,
  21080,
  24886,
  35632,
  35081,
  34177,
  19833,
  26295,
  21666,
  12855,
  40930,
  35561,
  31256,
  40154,
  32336,
  17048,
  15294,
  14540,
  19993,
  36373,
  16400,
  17143,
  33820,
  26320,
  15676,
  3669,
  27480,
  21106,
  18845,
  13893,
  41000,
  29951,
  41865,
  39877,
  26535,
  13986,
  18431,
  9423,
  22487,
  15542,
  12700,
  12311,
  30759,
  23032,
  35668,
  12839,
  28780,
  10029,
  43737,
  19668,
  6360,
  41468,
  14044,
  42847,
  36085,
  2336,
  29585,
  40833,
  39530,
  32646,
  30950,
  10017,
  6577,
  3413,
  20174,
  10280,
  17522,
  43860,
  45010,
  33165,
  22908,
  11950,
  26246,
  29441,
  19187,
  21592,
  20114,
  7579,
  44935,
  44385,
  38880,
  8311,
  1008,
  39137,
  24364,
  41767,
  35914,
  921,
  9047,
  14948,
  14111,
  15797,
  1360,
  31477,
  9718,
  39,
  12192,
  6042,
  10158,
  6024,
  30871,
  2245,
  43359,
  18350,
  20810,
  12122,
  20406,
  35968,
  35114,
  20806,
  34752,
  23284,
  33133,
  38256,
  37309,
  5559,
  27966,
  24004,
  6722,
  29635,
  21252,
  39401,
  45024,
  6731,
  19926,
  34079,
  45527,
  43604,
  41229,
  26789,
  13619,
  17329,
  13784,
  18477,
  12525,
  10945,
  21397,
  17939,
  16658,
  18746,
  3995,
  26252,
  27187,
  33246,
  13846,
  26804,
  32914,
  2063,
  9708,
  33828,
  4963,
  15361,
  6602,
  45185,
  24137,
  44347,
  18754,
  11552,
  30003,
  33116,
  43995,
  19528,
  41843,
  22356,
  33686,
  3092,
  15748,
  34820,
  2716,
  14753,
  26507,
  24271,
  14693,
  27849,
  32119,
  33680,
  16589,
  23701,
  4413,
  28081,
  31034,
  27997,
  42679,
  1834,
  16943,
  26067,
  14580,
  34754,
  43908,
  32332,
  21889,
  17771,
  43446,
  36776,
  28535,
  35707,
  8082,
  19552,
  20154,
  20415,
  23598,
  26426,
  ...],
 [11751,
  41765,
  1823,
  6200,
  45095,
  20577,
  12896,
  16776,
  22089,
  7264,
  30187,
  4397,
  579,
  10880,
  37987,
  41022,
  34261,
  4462,
  35994,
  12666,
  7723,
  1575,
  34147,
  21937,
  31980,
  36238,
  183,
  3507,
  43262,
  42072,
  3808,
  40886,
  42923,
  3737,
  19447,
  31572,
  17986,
  12065,
  37044,
  24454,
  20672,
  8055,
  21803,
  21959,
  1356,
  1228,
  4362,
  7157,
  41826,
  30732,
  26374,
  36574,
  18183,
  7611,
  22649,
  33376,
  35392,
  38171,
  13556,
  29647,
  31518,
  25304,
  18843,
  31373,
  8529,
  11931,
  32473,
  43730,
  39751,
  13660,
  37950,
  13102,
  19887,
  35337,
  39600,
  16182,
  32712,
  9475,
  6486,
  31116,
  14804,
  17549,
  14093,
  27811,
  23381,
  15589,
  10557,
  8794,
  35075,
  2267,
  41364,
  43683,
  38864,
  25107,
  39747,
  19403,
  4969,
  43857,
  11919,
  35858,
  16768,
  22846,
  25757,
  10845,
  17309,
  30953,
  26095,
  15781,
  40293,
  34744,
  17639,
  16755,
  18598,
  29502,
  24491,
  29832,
  42766,
  2316,
  36279,
  14977,
  18104,
  44659,
  3642,
  28511,
  36341,
  13733,
  12673,
  8172,
  36749,
  11363,
  25243,
  147,
  40400,
  6747,
  5222,
  29751,
  44875,
  43758,
  6137,
  32274,
  22384,
  5495,
  16355,
  24448,
  29156,
  33785,
  30790,
  39759,
  412,
  29707,
  30921,
  35054,
  33879,
  20671,
  35127,
  5508,
  41220,
  26719,
  39776,
  31642,
  31965,
  33506,
  29383,
  33715,
  6310,
  45175,
  45321,
  17397,
  29655,
  31260,
  24943,
  11969,
  17510,
  22293,
  36541,
  3562,
  42140,
  29952,
  414,
  38348,
  24852,
  31818,
  31050,
  40663,
  26522,
  7065,
  29184,
  25662,
  9284,
  33888,
  7385,
  14260,
  35893,
  38293,
  25298,
  40096,
  25846,
  37980,
  39833,
  19193,
  8583,
  23980,
  41079,
  8161,
  44904,
  42348,
  43259,
  27409,
  19646,
  29039,
  44933,
  39538,
  36264,
  43284,
  28154,
  43556,
  42720,
  24359,
  4807,
  42896,
  12509,
  35691,
  27993,
  43571,
  23948,
  4326,
  29428,
  40562,
  1304,
  16520,
  17111,
  17496,
  3976,
  39075,
  45260,
  8870,
  44149,
  38805,
  41450,
  28609,
  27343,
  41419,
  6331,
  41328,
  13115,
  44169,
  42180,
  33315,
  45241,
  28546,
  11973,
  9944,
  17634,
  24103,
  29788,
  10450,
  12346,
  22754,
  7958,
  33920,
  35552,
  12228,
  13105,
  26207,
  35817,
  10508,
  43722,
  4820,
  17637,
  45284,
  25047,
  10097,
  17649,
  19916,
  28139,
  45361,
  43267,
  1104,
  26343,
  23849,
  37392,
  13882,
  42710,
  31308,
  8360,
  22256,
  12135,
  23130,
  40088,
  12404,
  15222,
  9415,
  41598,
  12631,
  31608,
  20304,
  16581,
  6502,
  43419,
  4503,
  30657,
  29894,
  21368,
  42722,
  6052,
  12890,
  29789,
  22323,
  3101,
  39476,
  19212,
  16214,
  39979,
  38500,
  37574,
  24487,
  31331,
  22259,
  24749,
  34960,
  1452,
  31861,
  32982,
  38634,
  44329,
  29374,
  44373,
  2827,
  24396,
  31977,
  35967,
  7122,
  27679,
  43099,
  20182,
  8329,
  39171,
  35157,
  17618,
  19842,
  35537,
  20835,
  2948,
  38106,
  30145,
  30367,
  25164,
  31304,
  42680,
  13203,
  37211,
  4006,
  23669,
  37967,
  23910,
  13451,
  26929,
  44594,
  33399,
  39906,
  34297,
  34903,
  32600,
  13310,
  23643,
  44168,
  30666,
  23535,
  13596,
  37346,
  44572,
  15912,
  27885,
  10767,
  44100,
  9286,
  5170,
  24428,
  18367,
  5332,
  35927,
  45552,
  17285,
  27774,
  36944,
  36579,
  34292,
  44428,
  33843,
  25556,
  7243,
  15439,
  22969,
  26460,
  15357,
  3191,
  4297,
  37834,
  10799,
  24151,
  10079,
  2060,
  32915,
  16429,
  16805,
  21792,
  105,
  27277,
  15414,
  40332,
  14728,
  22072,
  27223,
  19619,
  42350,
  33163,
  37355,
  21447,
  38159,
  23416,
  28650,
  38186,
  6966,
  27205,
  10713,
  16000,
  32465,
  24834,
  45528,
  8298,
  40158,
  45440,
  31197,
  10693,
  5032,
  31976,
  27316,
  41603,
  38719,
  35033,
  42351,
  31446,
  32958,
  31815,
  19585,
  20751,
  22760,
  9948,
  43868,
  28323,
  16277,
  39676,
  3619,
  9129,
  6908,
  28965,
  13379,
  38370,
  28558,
  3938,
  9038,
  27729,
  15045,
  18906,
  27378,
  40883,
  9358,
  5157,
  21448,
  6784,
  45379,
  31497,
  41868,
  23760,
  12236,
  39959,
  21420,
  16352,
  3298,
  11235,
  44189,
  23919,
  21049,
  42666,
  3969,
  37598,
  30296,
  37535,
  32673,
  8398,
  5507,
  33507,
  17954,
  13838,
  27928,
  13164,
  11096,
  35717,
  29837,
  39668,
  18114,
  2974,
  27058,
  16201,
  26150,
  38717,
  20680,
  22955,
  36032,
  21822,
  34926,
  10542,
  42688,
  24587,
  35767,
  13314,
  16472,
  37467,
  36051,
  35254,
  1237,
  11270,
  13198,
  26466,
  27186,
  38113,
  8913,
  16993,
  29265,
  29807,
  13658,
  10734,
  10457,
  4144,
  13616,
  35984,
  5149,
  18011,
  44162,
  2218,
  45544,
  38820,
  21609,
  23398,
  20119,
  34931,
  7657,
  6337,
  44806,
  3579,
  41863,
  29034,
  13561,
  44284,
  26803,
  27496,
  30537,
  19438,
  21428,
  34100,
  41996,
  34760,
  11532,
  11897,
  17908,
  36924,
  22038,
  23297,
  28905,
  43551,
  18549,
  37514,
  23812,
  44273,
  27095,
  13916,
  15702,
  2645,
  45345,
  40511,
  12858,
  21631,
  26172,
  35485,
  26534,
  25282,
  8710,
  22724,
  17244,
  42284,
  14612,
  18106,
  24820,
  26147,
  17877,
  18155,
  40694,
  25501,
  2995,
  41595,
  11120,
  34067,
  18172,
  44683,
  33046,
  4808,
  26214,
  7043,
  44802,
  22195,
  26801,
  29771,
  39024,
  45574,
  34924,
  40910,
  13659,
  35915,
  29580,
  22255,
  30190,
  36250,
  23149,
  15872,
  38776,
  26842,
  31859,
  45350,
  13359,
  32967,
  33754,
  25388,
  36272,
  19142,
  32807,
  5471,
  41913,
  14719,
  28065,
  32050,
  11487,
  22815,
  24567,
  16741,
  7177,
  39167,
  7444,
  22050,
  13665,
  43425,
  30821,
  7294,
  30352,
  37354,
  14377,
  26808,
  27086,
  2290,
  28734,
  29292,
  4776,
  4122,
  14603,
  27475,
  9228,
  14005,
  22066,
  11479,
  15852,
  11515,
  21838,
  42484,
  24917,
  19759,
  20402,
  17358,
  37369,
  3414,
  44524,
  41206,
  4894,
  36580,
  44784,
  14244,
  9785,
  8874,
  39790,
  6813,
  12632,
  19868,
  7006,
  6867,
  41375,
  37770,
  36982,
  38290,
  34579,
  9310,
  33122,
  43713,
  32255,
  4469,
  40639,
  30264,
  24521,
  10074,
  28509,
  4810,
  10353,
  25991,
  9071,
  16494,
  41564,
  43902,
  35949,
  43664,
  1637,
  16109,
  45323,
  37778,
  33503,
  16484,
  32021,
  24459,
  3544,
  24099,
  6520,
  30402,
  20204,
  18432,
  27182,
  13018,
  9242,
  42581,
  34222,
  40739,
  23244,
  6933,
  23815,
  33387,
  30322,
  35604,
  2026,
  9203,
  42759,
  37570,
  16957,
  39493,
  20341,
  13202,
  24896,
  38670,
  9496,
  20412,
  40015,
  28779,
  36997,
  2023,
  26216,
  19624,
  17936,
  15229,
  15318,
  16065,
  7950,
  2543,
  15949,
  18699,
  41254,
  42334,
  16666,
  6836,
  21091,
  37796,
  16443,
  44239,
  27581,
  40811,
  20820,
  44811,
  28808,
  15418,
  43326,
  11104,
  20586,
  11822,
  11300,
  42305,
  28175,
  23516,
  17073,
  34197,
  33695,
  8347,
  30680,
  40170,
  16450,
  9408,
  14910,
  28337,
  37863,
  17010,
  41799,
  25161,
  41882,
  38413,
  39273,
  39598,
  11314,
  45585,
  20037,
  24456,
  3901,
  28346,
  5195,
  14205,
  41443,
  27022,
  44485,
  16859,
  13604,
  30613,
  27580,
  20089,
  20525,
  5234,
  11450,
  34277,
  25464,
  23021,
  21307,
  7772,
  36133,
  21678,
  36967,
  29501,
  18960,
  42004,
  27160,
  745,
  37545,
  27803,
  37847,
  28682,
  1435,
  11396,
  33980,
  11386,
  23513,
  32619,
  34655,
  37448,
  42301,
  32553,
  34989,
  44834,
  25920,
  43864,
  43969,
  24987,
  33049,
  30337,
  36733,
  44776,
  30257,
  29664,
  32385,
  25924,
  19446,
  7248,
  23942,
  17459,
  19785,
  5101,
  23145,
  7025,
  35895,
  3106,
  15097,
  6477,
  29747,
  2266,
  25409,
  26234,
  36315,
  39406,
  30122,
  32484,
  39251,
  3750,
  16896,
  33745,
  13859,
  17672,
  7220,
  42448,
  35894,
  11061,
  45236,
  42981,
  30394,
  26035,
  30662,
  26380,
  23420,
  42772,
  28448,
  8653,
  35788,
  34591,
  2432,
  40540,
  28748,
  42319,
  39303,
  16512,
  23370,
  29653,
  11682,
  44087,
  36129,
  8613,
  7582,
  5902,
  10986,
  21723,
  28880,
  41291,
  8655,
  16636,
  20251,
  40360,
  44918,
  26510,
  24285,
  44625,
  12699,
  17092,
  21661,
  43031,
  45034,
  26168,
  42065,
  18631,
  2403,
  14215,
  44624,
  44293,
  14085,
  21724,
  24347,
  29316,
  42854,
  31825,
  15458,
  5905,
  43154,
  15211,
  23563,
  27671,
  9523,
  19819,
  43296,
  39504,
  13221,
  13185,
  36107,
  42426,
  37974,
  26098,
  30146,
  8273,
  10913,
  29976,
  28236,
  38294,
  24579,
  3223,
  1560,
  3159,
  44251,
  27361,
  29936,
  17246,
  25722,
  27998,
  40286,
  11144,
  40769,
  27276,
  35336,
  19215,
  545,
  39800,
  24911,
  15818,
  10416,
  12732,
  37726,
  9978,
  ...],
 [37278,
  31095,
  23267,
  23943,
  22374,
  21315,
  18003,
  19486,
  2541,
  14223,
  40187,
  17291,
  11409,
  10292,
  28806,
  38338,
  14482,
  13072,
  26351,
  31415,
  22653,
  9777,
  27008,
  11154,
  23877,
  41342,
  11595,
  9090,
  14270,
  3205,
  17928,
  2474,
  25103,
  16782,
  39988,
  25878,
  6033,
  43966,
  33525,
  10500,
  3105,
  20714,
  40664,
  31345,
  37400,
  44929,
  2247,
  35647,
  44795,
  33553,
  26677,
  9663,
  23499,
  20604,
  18949,
  35745,
  14070,
  7395,
  40914,
  18814,
  38638,
  22745,
  21153,
  25042,
  12052,
  12956,
  22108,
  19108,
  21540,
  18546,
  15128,
  29948,
  10172,
  24686,
  44924,
  27814,
  6672,
  36394,
  5670,
  463,
  17702,
  26990,
  41698,
  27011,
  15586,
  37937,
  44895,
  44392,
  35639,
  9651,
  6704,
  31403,
  18134,
  18608,
  12714,
  8141,
  15730,
  16394,
  13257,
  38059,
  14653,
  43783,
  40555,
  10521,
  20002,
  29258,
  25496,
  19749,
  9795,
  18384,
  45103,
  44331,
  10311,
  2481,
  40654,
  18721,
  14639,
  6562,
  17141,
  19542,
  19107,
  34426,
  35444,
  21997,
  8044,
  32251,
  28483,
  15337,
  28892,
  32781,
  20428,
  2067,
  28173,
  35558,
  36248,
  15098,
  43607,
  44122,
  42636,
  43341,
  34589,
  9691,
  41334,
  28974,
  21376,
  23735,
  17122,
  8946,
  37572,
  42948,
  13831,
  24534,
  23358,
  40431,
  39306,
  22628,
  340,
  21762,
  33075,
  24765,
  8960,
  6721,
  4072,
  30488,
  29128,
  27706,
  31999,
  8527,
  12405,
  23364,
  45265,
  41274,
  15780,
  35328,
  31602,
  40308,
  22996,
  35925,
  11166,
  31712,
  7303,
  5960,
  14827,
  10596,
  20833,
  23903,
  19460,
  35087,
  40653,
  9380,
  6027,
  15086,
  17415,
  42618,
  11723,
  20727,
  28667,
  611,
  5845,
  12984,
  35355,
  16441,
  29398,
  8915,
  34020,
  41907,
  34797,
  43977,
  40339,
  41824,
  18377,
  34130,
  34121,
  29791,
  13090,
  43615,
  13935,
  16080,
  43011,
  36111,
  16386,
  18438,
  17841,
  40398,
  32727,
  9182,
  35987,
  42942,
  20957,
  38231,
  40232,
  17555,
  38538,
  36072,
  42286,
  30237,
  11966,
  32098,
  42007,
  6359,
  16169,
  8819,
  13087,
  16919,
  4485,
  11604,
  16127,
  31566,
  3469,
  23623,
  24618,
  27540,
  34227,
  12980,
  21942,
  4914,
  39703,
  30677,
  42853,
  361,
  36446,

In [ ]:
test_set_idx_3 = np.concatenate(test_set_idx_3).tolist()

In [ ]:
test_set_idx_3

[21778,
 44839,
 25999,
 17974,
 4578,
 35836,
 28812,
 12637,
 7648,
 14149,
 38997,
 22341,
 16126,
 45122,
 30318,
 17254,
 36753,
 36922,
 33492,
 36236,
 31478,
 44042,
 29260,
 21040,
 33985,
 24465,
 37244,
 13744,
 34209,
 35371,
 43494,
 9655,
 33180,
 4173,
 2573,
 39506,
 18137,
 16518,
 37046,
 45067,
 22674,
 23808,
 19090,
 26604,
 45536,
 19290,
 3763,
 36730,
 13663,
 44350,
 45341,
 23496,
 16914,
 11687,
 23726,
 21506,
 8959,
 12222,
 32537,
 15135,
 15259,
 41700,
 8421,
 5580,
 35427,
 25480,
 3667,
 44906,
 17816,
 44859,
 38735,
 40428,
 38919,
 4518,
 42607,
 38262,
 28017,
 25227,
 11405,
 39563,
 1634,
 42112,
 20887,
 11026,
 21799,
 25509,
 7530,
 45506,
 4161,
 17619,
 19787,
 31189,
 9642,
 45262,
 22650,
 31012,
 40035,
 44892,
 39407,
 21483,
 17105,
 32338,
 20377,
 40836,
 8377,
 16486,
 39083,
 40964,
 25656,
 30869,
 21306,
 20851,
 27235,
 11975,
 17193,
 7105,
 34505,
 21150,
 34208,
 42184,
 38421,
 29656,
 12904,
 19267,
 21722,
 4182,
 44308,
 25902,
 23394,
 24418,
 21273,
 20287,
 45301,
 43235,
 42644,
 45021,
 35043,
 23079,
 35998,
 16337,
 36963,
 41979,
 7970,
 32913,
 28925,
 31793,
 29916,
 39554,
 28292,
 44678,
 13309,
 34170,
 42477,
 43570,
 34580,
 20974,
 34389,
 25957,
 28245,
 19694,
 44788,
 24397,
 4350,
 11507,
 3652,
 10402,
 31165,
 10112,
 11090,
 45078,
 27750,
 1443,
 44146,
 12368,
 40882,
 28315,
 25183,
 45244,
 25376,
 26787,
 43279,
 5655,
 40733,
 36147,
 34394,
 11586,
 30091,
 7450,
 30513,
 18507,
 9505,
 41295,
 21571,
 13392,
 26982,
 17235,
 12330,
 18082,
 21843,
 35297,
 33964,
 6941,
 36347,
 33883,
 42787,
 16694,
 6213,
 16564,
 20239,
 10959,
 19666,
 27857,
 17269,
 41044,
 43802,
 26205,
 27023,
 26752,
 16304,
 39126,
 6688,
 28519,
 21249,
 11110,
 41536,
 22721,
 28157,
 44569,
 14136,
 36855,
 25233,
 3214,
 42808,
 14308,
 30401,
 21645,
 33186,
 7646,
 14739,
 2841,
 29336,
 33606,
 17668,
 37606,
 29136,
 12565,
 31855,
 43178,
 38090,
 37408,
 3125,
 12324,
 38878,
 15563,
 17332,
 13703,
 5116,
 39908,
 35256,
 40823,
 24558,
 12318,
 37845,
 41712,
 34510,
 8908,
 34449,
 26058,
 42567,
 27744,
 9027,
 33253,
 3549,
 15502,
 33867,
 42325,
 33092,
 36613,
 17747,
 21492,
 27726,
 37693,
 16530,
 6175,
 34763,
 16553,
 24289,
 1848,
 20121,
 18638,
 16855,
 11327,
 17815,
 22076,
 1405,
 9634,
 19402,
 18181,
 28165,
 33808,
 24245,
 17929,
 37984,
 38218,
 42333,
 10026,
 17675,
 25542,
 7554,
 14107,
 517,
 44663,
 31844,
 42382,
 28055,
 37892,
 13824,
 24676,
 4396,
 5449,
 30347,
 43874,
 9165,
 27342,
 17922,
 11230,
 25395,
 34890,
 40005,
 22194,
 34766,
 27165,
 38841,
 24393,
 45510,
 2619,
 5265,
 44048,
 15552,
 30302,
 297,
 31915,
 43433,
 13571,
 13129,
 17239,
 38875,
 42894,
 44955,
 5829,
 12288,
 29139,
 4839,
 14500,
 22354,
 14678,
 40838,
 19524,
 18230,
 25693,
 30652,
 4091,
 41558,
 45192,
 9821,
 8061,
 29663,
 17293,
 44857,
 17027,
 29718,
 38170,
 34819,
 43380,
 4051,
 17000,
 26915,
 21148,
 29706,
 27149,
 31052,
 45311,
 8008,
 20587,
 38034,
 9091,
 45019,
 36793,
 18535,
 23677,
 13325,
 33280,
 27622,
 8019,
 38837,
 32855,
 21836,
 749,
 20803,
 30031,
 38306,
 26090,
 24893,
 32159,
 42368,
 12549,
 36082,
 29021,
 21885,
 35061,
 40395,
 39026,
 41488,
 22274,
 32062,
 27167,
 34283,
 34804,
 33751,
 3147,
 42667,
 24254,
 27705,
 45360,
 937,
 41772,
 13048,
 37008,
 4581,
 42326,
 4250,
 37741,
 40195,
 40826,
 20215,
 18087,
 8226,
 18937,
 29372,
 15592,
 8911,
 18886,
 43363,
 20399,
 20709,
 13795,
 33177,
 44709,
 22032,
 12775,
 18620,
 14509,
 18476,
 16956,
 43128,
 19920,
 26673,
 23029,
 42574,
 18450,
 18239,
 20923,
 15030,
 7070,
 22810,
 14766,
 22039,
 13758,
 4209,
 13354,
 35773,
 15219,
 29815,
 12694,
 9897,
 27708,
 45330,
 17207,
 30312,
 25445,
 15091,
 33037,
 16939,
 30669,
 37715,
 6990,
 10256,
 10310,
 10102,
 33478,
 7460,
 22523,
 19303,
 45395,
 38278,
 19371,
 35548,
 32942,
 43964,
 42603,
 17487,
 12299,
 9247,
 39066,
 16847,
 26228,
 20443,
 41768,
 15326,
 8846,
 23265,
 4111,
 18706,
 17885,
 20087,
 28993,
 38485,
 24146,
 42306,
 25452,
 40825,
 5067,
 29169,
 12286,
 28904,
 11434,
 28952,
 26665,
 41483,
 19824,
 21430,
 28770,
 39873,
 13433,
 13719,
 8375,
 8424,
 38074,
 44983,
 42450,
 17608,
 15411,
 4363,
 21814,
 40274,
 33195,
 37478,
 37333,
 22530,
 35606,
 43163,
 7430,
 1946,
 35955,
 8933,
 11095,
 44379,
 6660,
 43132,
 45141,
 2404,
 34637,
 18760,
 31386,
 37637,
 37775,
 12208,
 33989,
 18603,
 39146,
 44962,
 36736,
 24112,
 38070,
 34910,
 39516,
 37454,
 12895,
 41696,
 20482,
 35993,
 33412,
 19473,
 40629,
 44197,
 26369,
 17301,
 23603,
 36108,
 22324,
 8792,
 36853,
 7477,
 43676,
 15620,
 26549,
 32641,
 14855,
 36257,
 20876,
 42194,
 17732,
 44762,
 21429,
 1635,
 15014,
 5509,
 28207,
 32552,
 34826,
 15260,
 19644,
 19560,
 43559,
 24490,
 7829,
 1301,
 17386,
 6591,
 37559,
 35683,
 26884,
 38759,
 25584,
 26001,
 20365,
 38091,
 14145,
 27635,
 33670,
 19908,
 220,
 7783,
 14575,
 24971,
 38708,
 6203,
 2004,
 29619,
 12590,
 45108,
 21406,
 24346,
 27500,
 31747,
 25701,
 19475,
 23658,
 41347,
 13076,
 45195,
 43775,
 15005,
 28658,
 36689,
 36434,
 37279,
 7547,
 5587,
 25742,
 20058,
 13330,
 16760,
 7790,
 19028,
 44040,
 36969,
 43933,
 43755,
 1233,
 42387,
 3949,
 29596,
 33704,
 40820,
 25974,
 42647,
 12771,
 17032,
 11276,
 32115,
 14450,
 19352,
 40544,
 16073,
 44147,
 37050,
 35052,
 35024,
 8189,
 16018,
 15725,
 10793,
 15953,
 42219,
 23215,
 29572,
 8374,
 44726,
 42669,
 16958,
 29979,
 9530,
 29314,
 41820,
 23842,
 39294,
 22230,
 9763,
 34096,
 13742,
 41197,
 40175,
 8661,
 45145,
 23037,
 28842,
 43671,
 22078,
 32607,
 41418,
 15274,
 40932,
 40766,
 13942,
 6924,
 35794,
 10110,
 19643,
 39763,
 27020,
 18682,
 13031,
 9421,
 7943,
 5604,
 23853,
 44490,
 27971,
 14155,
 17196,
 13339,
 18556,
 34968,
 24605,
 16736,
 6648,
 25495,
 31878,
 14522,
 24711,
 9498,
 24064,
 10057,
 42406,
 26183,
 3115,
 33658,
 44232,
 38386,
 13670,
 11559,
 26540,
 24016,
 33722,
 10633,
 40789,
 15790,
 40305,
 38273,
 41519,
 22871,
 30100,
 5154,
 19620,
 24777,
 12620,
 19305,
 44026,
 23156,
 39577,
 25073,
 33353,
 12196,
 3093,
 12617,
 9034,
 25337,
 19263,
 4229,
 28099,
 39572,
 30109,
 26221,
 36854,
 13778,
 15714,
 24879,
 37639,
 21080,
 24886,
 35632,
 35081,
 34177,
 19833,
 26295,
 21666,
 12855,
 40930,
 35561,
 31256,
 40154,
 32336,
 17048,
 15294,
 14540,
 19993,
 36373,
 16400,
 17143,
 33820,
 26320,
 15676,
 3669,
 27480,
 21106,
 18845,
 13893,
 41000,
 29951,
 41865,
 39877,
 26535,
 13986,
 18431,
 9423,
 22487,
 15542,
 12700,
 12311,
 30759,
 23032,
 35668,
 12839,
 28780,
 10029,
 43737,
 19668,
 6360,
 41468,
 14044,
 42847,
 36085,
 2336,
 29585,
 40833,
 39530,
 32646,
 30950,
 10017,
 6577,
 3413,
 20174,
 10280,
 17522,
 43860,
 45010,
 33165,
 22908,
 11950,
 26246,
 29441,
 19187,
 21592,
 20114,
 7579,
 44935,
 44385,
 38880,
 8311,
 1008,
 39137,
 24364,
 41767,
 35914,
 921,
 9047,
 14948,
 14111,
 15797,
 1360,
 31477,
 9718,
 39,
 12192,
 6042,
 10158,
 6024,
 30871,
 2245,
 43359,
 18350,
 20810,
 12122,
 20406,
 35968,
 35114,
 20806,
 34752,
 23284,
 33133,
 38256,
 37309,
 5559,
 27966,
 24004,
 6722,
 29635,
 21252,
 39401,
 45024,
 6731,
 19926,
 34079,
 45527,
 43604,
 41229,
 26789,
 13619,
 17329,
 13784,
 18477,
 12525,
 10945,
 21397,
 17939,
 16658,
 18746,
 3995,
 26252,
 27187,
 33246,
 13846,
 26804,
 32914,
 2063,
 9708,
 33828,
 4963,
 15361,
 6602,
 45185,
 24137,
 44347,
 18754,
 11552,
 30003,
 33116,
 43995,
 19528,
 41843,
 22356,
 33686,
 3092,
 15748,
 34820,
 2716,
 14753,
 26507,
 24271,
 14693,
 27849,
 32119,
 33680,
 16589,
 23701,
 4413,
 28081,
 31034,
 27997,
 42679,
 1834,
 16943,
 26067,
 14580,
 34754,
 43908,
 32332,
 21889,
 17771,
 43446,
 36776,
 28535,
 35707,
 8082,
 19552,
 20154,
 20415,
 23598,
 26426,
 ...]

In [ ]:
len(test_set_idx_3)

7871

In [ ]:
test_set = user_log[user_log['user_idx'].isin(test_set_idx_3)]
test_set = test_set.sort_values(by='user_idx', ascending=True)

In [ ]:
test_set

        user_idx     id
6              2   4917
7              2   9200
8              2  11935
9              2   2505
10             2   9596
...          ...    ...
241730     45584   4385
241733     45585   9681
241734     45585   9663
241732     45585   9649
241735     45585  11100

[46861 rows x 2 columns]

In [ ]:
train_set_idx = [x for x in total_user_idx if x not in test_set_idx_3]

In [ ]:
train_set = user_log[user_log['user_idx'].isin(train_set_idx)]
train_set = train_set.sort_values(by='user_idx', ascending=True)

In [ ]:
train_set

        user_idx     id
0              0  11602
1              0   6080
2              0   2385
3              0   6076
4              0   6077
...          ...    ...
241737     45586    511
241741     45587   5061
241742     45587  11955
241740     45587   6600
241743     45587   5706

[187568 rows x 2 columns]